test matrix failure

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -38,8 +38,8 @@ jobs:
             python: "3.10"
     steps:
       - run: |
-        echo "This should fail"
-        exit 1
+          echo "This should fail"
+          exit 1
       - uses: actions/checkout@v3
       - run: pipx install poetry
       - uses: actions/setup-python@v4
